### ISSUE TITLE
Inconsistency when determining year

### ISSUE THREAD

**Issue by mariuszwicker-cnhind** [emzeat/mz-lictools#30]
When amending to a commit the constructor for an Author is using `DateUtils` resulting in the current year to be used
```py
...
if year_to is None:
  year_to = DateUtils.current_year()
...
```
However when checking the git history is used with the date a commit was _created_, not amended:
```py
...
author_raw = subprocess.check_output(
                f'git log -1 --date=format:%Y --pretty=format:"%an\t%ad" -- {file_rel}',
                cwd=self.git_root, stderr=subprocess.STDOUT, shell=True,
                encoding='utf-8')
...
```

This is causing a mismatch by using author date "%ad", not commit date "%ac".

**Comment by mariuszwicker-cnhind** [comment]
See https://git-scm.com/docs/pretty-formats for supported formats.

**Comment by emzeat** [comment]
Using the commit date would break handling of importing patch files via `git am` as this is also using a current commit date.

One alternative might be to make `git commit --amend` update the commit date via `git commit --amend --date=now` solving the inconsistency as it is right now. This is not very intuitive though.
